"""Pydantic schemas for traffic law query endpoints."""

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field


class QueryRequest(BaseModel):
    """User query payload."""

    model_config = ConfigDict(extra="forbid")

    query: str = Field(
        ...,
        min_length=2,
        max_length=500,
        description="Colloquial citizen question regarding traffic laws or violations",
        examples=["Vượt đèn đỏ xe máy bị phạt bao nhiêu tiền và có bị trừ điểm bằng lái không?"],
    )
    document_id: str | None = Field(
        default=None,
        description="Optional canonical document ID to constrain retrieval (e.g., '168_2024_ND-CP')",
        examples=["168_2024_ND-CP"],
    )
    top_k: int = Field(
        default=5,
        ge=1,
        le=20,
        description="Number of top candidate legal chunks to retrieve",
    )
    include_subgraph: bool = Field(
        default=True,
        description="Whether to include visualized knowledge subgraph (nodes and edges) in the response",
    )


class CitationItem(BaseModel):
    """Statutory citation reference."""

    citation: str = Field(..., description="Legal citation (e.g. 'Điểm a Khoản 1 Điều 5')")
    document_id: str | None = Field(default=None, description="Document identifier")
    url_reference: str | None = Field(default=None, description="Official reference URL if available")


class SubGraphNodeSchema(BaseModel):
    """Knowledge subgraph node representation for UI visualization."""

    id: str
    label: str
    properties: dict[str, Any] = Field(default_factory=dict)


class SubGraphEdgeSchema(BaseModel):
    """Knowledge subgraph directed relationship representation."""

    source: str
    target: str
    type: str
    properties: dict[str, Any] = Field(default_factory=dict)


class SubGraphSchema(BaseModel):
    """Visualized knowledge subgraph returned with query answers."""

    nodes: list[SubGraphNodeSchema] = Field(default_factory=list)
    relationships: list[SubGraphEdgeSchema] = Field(default_factory=list)


class QueryResponse(BaseModel):
    """Grounded query response from GraphRAG pipeline."""

    status: Literal["success", "out_of_scope", "error"] = Field(
        default="success", description="Query execution status"
    )
    user_query: str = Field(..., description="Original citizen query")
    search_query: str = Field(..., description="Formal statutory search query generated by rewriter")
    intent: str = Field(..., description="Classified intent (violation_sanction, document_amendment, etc.)")
    answer: str = Field(..., description="Grounded legal answer produced by LLM")
    citations: list[str] = Field(default_factory=list, description="Extracted statutory citations")
    subgraph: SubGraphSchema | None = Field(
        default=None, description="Knowledge subgraph related to query provisions"
    )
    execution_time_ms: float = Field(..., description="Total processing latency in milliseconds")
    grounding_verified: bool = Field(
        default=True, description="Whether the answer passed action grounding guardrails"
    )
    verification_warnings: list[str] = Field(
        default_factory=list, description="Warning flags raised during verification"
    )


class StreamChunkEvent(BaseModel):
    """Event chunk emitted over Server-Sent Events (SSE)."""

    event: Literal["stage", "token", "subgraph", "done", "error"]
    data: dict[str, Any]
